### ISSUE TITLE
Tree survey - height data

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/ccha-workflow#13]
plz add tree height as an option in the summary variable drop-down, it should be in the google sheet.

**Comment by fawda123** [comment]
Done, these are just reported as the average for a species at the site/zone level or across all species at the site/zone level.

**Comment by Gmangrove** [comment]
I'm not seeing where to select tree height?

![image](https://user-images.githubusercontent.com/49997266/152784962-1ce1c64b-ed13-49e7-b096-42412c876691.png)

**Comment by fawda123** [comment]
Whoops, forgot to pull the changes to the server.  Try it now.

**Comment by Gmangrove** [comment]
Yep, I can see them now! However, the tree height columns shouldn't be stacked, pretty sure we don't have trees growing on top of trees ;0)

**Comment by fawda123** [comment]
Added a little switch to stack...
![image](https://user-images.githubusercontent.com/3086881/152882279-e0963ba8-55cb-442c-8d07-6fc487ffdd55.png)
or not...
![image](https://user-images.githubusercontent.com/3086881/152882337-89d7c04e-f867-419e-8442-e1e21c5dd441.png)
